version: '2.3'
services:
  service1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SERVICE_NAME=service1
      - PORT=8080
      - NEXT_SERVICE=http://service2:8081,http://service3:8082
    depends_on:
      - service2
      - service3

  service2:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - SERVICE_NAME=service2
      - PORT=8081
    depends_on: []

  service3:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - SERVICE_NAME=service3
      - PORT=8082
      - NEXT_SERVICE=http://service4:8083
    depends_on: []

  service4:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - SERVICE_NAME=service4
      - PORT=8083
    depends_on: []
